image: "registry.gitlab.com/manveru/finesco"
before_script:

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - site build
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
