#!/usr/bin/env bash

set -ex

ghc --make site.hs

(
  find . -name site.hs | entr -n -r -s 'ghc --make site.hs' &
  find . -name site | entr -n -r -s './site clean && ./site watch'
)

# docker run -it \
#   -p 35729:35729 \
#   -v "$(pwd)/_site:/site" \
#   --restart always \
#   --name livereloadx \
#   node:alpine /bin/ash -c \
#   "npm install -g --log-level=error livereloadx; \
#   livereloadx -s /site"
